server.port=${port:8080}

#Actuator
management.endpoints.web.exposure.include=env,info,shutdown,mappings,beans,health,metrics,threaddump,heapdump
management.endpoint.env.show-values=always
management.endpoint.shutdown.access=unrestricted

spring.datasource.url=jdbc:postgresql://localhost:5432/database37
spring.datasource.username=user37
spring.datasource.password=root

logging.level.root=INFO
logging.file.name=logs/grouplogs37.log